roles:
  - name: geerlingguy.mysql
    version: "5.0.2"

  - name: geerlingguy.nginx
    version: "3.2.0"

  - name: stackhpc.openhpc
    version: "v1.2.0"

  - name: linux-system-roles.postfix
    version: "1.6.0"

collections:
  - name: freeipa.ansible_freeipa
    version: "1.14.7"
