roles:
  - name: geerlingguy.mysql
    version: "5.1.0"

  - name: geerlingguy.nginx
    version: "3.2.0"

  - name: stackhpc.openhpc
    version: "v1.3.0"

  - name: linux-system-roles.postfix
    version: "1.6.4"

collections:
  - name: freeipa.ansible_freeipa
    version: "1.15.1"
