- name: Get home dir path
  ansible.builtin.shell: pwd
  register: dir

- name: Assert home dir path is correct
  ansible.builtin.fail:
    msg: "Bad home dir path"
  when:
    - dir.rc != 0 or dir.stdout.strip() != "/home/" + ansible_user

- name: Get df
  ansible.builtin.shell: df
  register: df

- name: Assert mountpoint is correct
  ansible.builtin.fail:
    msg: "Missing mount in df"
  when:
    - df.rc != 0 or  'mgmt.{{domain}}:/mnt/rds1/home' not in df.stdout

- name: Get srun node hostnames
  ansible.builtin.shell: srun --nodelist={{node}} hostname
  register: srun
  until: srun.rc == 0
  retries: 30 # 3 minutes
  delay: 1
  loop: "{{nodes.keys()}}"
  loop_control: { loop_var: node }

- ansible.builtin.fail:
    msg: "Bad srun outcome"
  when: result.rc != 0 or result.stdout.strip() != result.node
  loop: "{{srun.results}}"
  loop_control: { loop_var: result }
